# .air.toml configuration
[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  full_bin = false
  include_ext = ["go"]
  exclude_dir = ["frontend"]

[log]
  level = "debug"

[http]
  addr = "localhost:9090"
  url = "http://localhost:9090"
